"""nested_set_model

Revision ID: 454d1d76049a
Revises: a21255c4781a
Create Date: 2016-10-29 19:10:32.416766

"""

# revision identifiers, used by Alembic.
revision = '454d1d76049a'
down_revision = 'a21255c4781a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nested_set_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=True),
    sa.Column('rgt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nested_set_model_lft'), 'nested_set_model', ['lft'], unique=False)
    op.create_index(op.f('ix_nested_set_model_parent_id'), 'nested_set_model', ['parent_id'], unique=False)
    op.create_index(op.f('ix_nested_set_model_rgt'), 'nested_set_model', ['rgt'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nested_set_model_rgt'), table_name='nested_set_model')
    op.drop_index(op.f('ix_nested_set_model_parent_id'), table_name='nested_set_model')
    op.drop_index(op.f('ix_nested_set_model_lft'), table_name='nested_set_model')
    op.drop_table('nested_set_model')
    ### end Alembic commands ###
