"""empty message

Revision ID: 495aecf988c2
Revises: a8ec7d3291c9
Create Date: 2016-10-07 23:13:51.164013

"""

# revision identifiers, used by Alembic.
revision = '495aecf988c2'
down_revision = 'a8ec7d3291c9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import LtreeType



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('second_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('path', LtreeType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_second_model_parent_id'), 'second_model', ['parent_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_second_model_parent_id'), table_name='second_model')
    op.drop_table('second_model')
    ### end Alembic commands ###
