"""materialized_path__model

Revision ID: a21255c4781a
Revises: c4eae3aacecd
Create Date: 2016-10-29 19:08:05.792279

"""

# revision identifiers, used by Alembic.
revision = 'a21255c4781a'
down_revision = 'c4eae3aacecd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import LtreeType


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materialized_path_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('path', LtreeType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materialized_path_model_parent_id'), 'materialized_path_model', ['parent_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materialized_path_model_parent_id'), table_name='materialized_path_model')
    op.drop_table('materialized_path_model')
    ### end Alembic commands ###
