"""empty message

Revision ID: a8ec7d3291c9
Revises: None
Create Date: 2016-10-04 21:08:59.067566

"""

# revision identifiers, used by Alembic.
revision = 'a8ec7d3291c9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('first_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_model_parent_id'), 'first_model', ['parent_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_first_model_parent_id'), table_name='first_model')
    op.drop_table('first_model')
    ### end Alembic commands ###
