"""adjcenty_list_model

Revision ID: c4eae3aacecd
Revises: None
Create Date: 2016-10-29 19:06:59.655324

"""

# revision identifiers, used by Alembic.
revision = 'c4eae3aacecd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjcency_list_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjcency_list_model_parent_id'), 'adjcency_list_model', ['parent_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adjcency_list_model_parent_id'), table_name='adjcency_list_model')
    op.drop_table('adjcency_list_model')
    ### end Alembic commands ###
