"""empty message

Revision ID: e6480f8db3c5
Revises: 495aecf988c2
Create Date: 2016-10-24 16:42:47.730106

"""

# revision identifiers, used by Alembic.
revision = 'e6480f8db3c5'
down_revision = '495aecf988c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nested_set_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=True),
    sa.Column('rgt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nested_set_model_lft'), 'nested_set_model', ['lft'], unique=False)
    op.create_index(op.f('ix_nested_set_model_parent_id'), 'nested_set_model', ['parent_id'], unique=False)
    op.create_index(op.f('ix_nested_set_model_rgt'), 'nested_set_model', ['rgt'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nested_set_model_rgt'), table_name='nested_set_model')
    op.drop_index(op.f('ix_nested_set_model_parent_id'), table_name='nested_set_model')
    op.drop_index(op.f('ix_nested_set_model_lft'), table_name='nested_set_model')
    op.drop_table('nested_set_model')
    ### end Alembic commands ###
